services:
  php:
      build: .
      user: 1000:1000
      container_name: chess_api_php
      restart: always
      volumes:
          - ./:/usr/share/nginx/chess-api
          - /usr/share/nginx/chess-api/vendor
          - ./docker/php/8.3/cli/php.ini:/usr/local/etc/php/php.ini
      working_dir: /usr/share/nginx/chess-api
  nginx:
      image: nginx:1.20
      container_name: chess_api_nginx
      ports:
          - "9443:9443"
      restart: always
      volumes:
          - ./:/usr/share/nginx/chess-api
          - /usr/share/nginx/chess-api/vendor
          - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
          - ./docker/nginx/ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem
          - ./docker/nginx/ssl/privkey.pem:/etc/nginx/ssl/privkey.pem
      working_dir: /usr/share/nginx/chess-api
